name: 'Setup Firefox ^_-'
description: 'Installs Firefox on Linux'
branding:
  icon: "arrow-up-right"
  color: "orange"
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: firefox.sh
      shell: bash